version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Lambda function
      - zip -r lambda_function.zip lambda/tagging/lambda_function.py

artifacts:
  files:
    - lambda_function.zip
